# Generated by Django 2.2.7 on 2021-06-07 01:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='latest_post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 1, 12, 14, 696191, tzinfo=utc)),
        ),
    ]
