# Generated by Django 2.2.7 on 2019-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191206_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default='Welcome to my blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.TextField(unique=True),
        ),
    ]
