# Generated by Django 2.2.7 on 2021-06-07 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210607_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='latest_post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 1, 13, 0, 528955, tzinfo=utc)),
        ),
    ]
