# Generated by Django 2.2.7 on 2020-01-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postDate',
            new_name='creation_date',
        ),
    ]
