# Generated by Django 2.2.7 on 2020-01-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200105_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentedPost',
            new_name='commented_post',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default='Welcome to my blog', max_length=600),
        ),
    ]
